name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        
    - name: Find out some info about where java is installed
      run: java --version && which java && pwd && echo $JAVA_HOME

    - name: Test with Bazel
      run: ./bazel test --verbose_failures //...
