name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up Zulu JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Prepare .bazelrc file
      run:  cat bazelrc.tmpl | sed s+xxxxxx+"$JAVA_HOME"+ > .bazelrc

    - name: Test with Bazel
      run: ./bazel test --verbose_failures //...
